# Config to extract melspeciv, linspeciv, melspecgcc, linspecgcc feature for TAU-NIGENS Spatial Sound Events (TNSSE) 2021 dataset
data_dir: '/media/tho_nguyen/disk1/audio_datasets/dcase2021/task3'
feature_dir: '/media/tho_nguyen/disk2/new_seld/dcase2021/features'
data:
  format: 'foa'
  fs: 24000
  n_fft: 512
  win_len: 512
  hop_len: 300  # 240 for 10ms, 300 for 12.5ms, 480 for 20 ms
  fmin: 50
  fmax: 12000
  n_mels: 128
